#  Created in Dart by Andres Garcia (TECH-ANDGAR) on 2025-01-03.
name: 'demo_test_technical_flutter_202501'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: 'flutter'
  flutter_riverpod: '^2.6.1'
  go_router: '^14.3.0'

dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
  dart_code_linter: '^1.1.5'
  mocktail: ^1.0.4
  flutter_coverage_badge:
    git:
      url: https://github.com/foresightmobile/flutter_coverage_badge
      ref: 4d6371f1bd46fee1bd28a697e303412839e53548

flutter:
  uses-material-design: true
  fonts:
    - family: 'Futura Book Italic'
      fonts:
        - asset: 'fonts/Futura Book Italic font.ttf'
          weight: 400
          style: 'italic'
    - family: 'futur'
      fonts:
        - asset: 'fonts/futur.ttf'
    - family: 'futura light bt'
      fonts:
        - asset: 'fonts/futura light bt.ttf'
          weight: 300
    - family: 'Futura Extra Black'
      fonts:
        - asset: 'fonts/Futura Extra Black font.ttf'
          weight: 900
    - family: 'futura medium condensed bt'
      fonts:
        - asset: 'fonts/futura medium condensed bt.ttf'
          weight: 400
    - family: 'Futura Medium Italic'
      fonts:
        - asset: 'fonts/Futura Medium Italic font.ttf'
          weight: 400
          style: 'italic'
    - family: 'Futura Heavy Italic'
      fonts:
        - asset: 'fonts/Futura Heavy Italic font.ttf'
          weight: 400
          style: 'italic'
    - family: 'Futura Light Italic'
      fonts:
        - asset: 'fonts/Futura Light Italic font.ttf'
          weight: 400
          style: 'italic'
    - family: 'tt0205m '
      fonts:
        - asset: 'fonts/tt0205m_.ttf'
    - family: 'Futura Bold'
      fonts:
        - asset: 'fonts/Futura Bold font.ttf'
          weight: 700
    - family: 'Futura Heavy'
      fonts:
        - asset: 'fonts/Futura Heavy font.ttf'
    - family: 'Futura Book'
      fonts:
        - asset: 'fonts/Futura Book font.ttf'
    - family: 'unicode.futurab'
      fonts:
        - asset: 'fonts/unicode.futurab.ttf'
    - family: 'futura medium bt'
      fonts:
        - asset: 'fonts/futura medium bt.ttf'
          weight: 500
    - family: 'Futura Light'
      fonts:
        - asset: 'fonts/Futura Light font.ttf'
          weight: 300
    - family: 'Futura XBlk BT'
      fonts:
        - asset: 'fonts/Futura XBlk BT.ttf'
    - family: 'Futura Bold Italic'
      fonts:
        - asset: 'fonts/Futura Bold Italic font.ttf'
          weight: 400
          style: 'italic'
    - family: 'unicode.futurabb'
      fonts:
        - asset: 'fonts/unicode.futurabb.ttf'
